#!/usr/bin/env bash

THIS_DIR="$(realpath "$(dirname "${BASH_SOURCE[0]}")")"
cd "${THIS_DIR}/.." || exit $?

# creates an example HTML file using random docs I have
exec markdown_stew -dark-mode -title 'example docs' './README.md' "$REPOS/HPI/doc/MAIL_SETUP.md" "$REPOS/HPI/doc/TROUBLESHOOTING_INSTALLS.md" "$REPOS/albums/requirements.txt"
